accounts/urls.py
from django.urls import path
from .import views
app_name = "accounts"
urlpatterns=[
    path('dashboard',views.dashboard,name="dashboard"),
    path('profile/<int:user_id>',views.profile,name="profile"),
    path('dashboard/bid/<int:bid_id>/delete', views.delete_bid, name="delete_bid"),
    path('profile/<int:user_id>/change_email', views.change_email, name="change_email"),
    path('profile/<int:user_id>/change_password', views.change_password, name="change_password"),
]

app/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    path('', views.index, name="index"),
    path('register', views.registration, name="registration"),
    path('user_login', views.custom_login, name="custom_login"),
    path('job_form', views.job_form, name="job_form"),
    path('job_form/save', views.save_job, name="save_job"),
    path('all_jobs', views.all_jobs, name="all_jobs"),
    path('all_jobs/bid/<int:job_id>', views.bid, name="bid"),
    path('all_jobs/send_message/<int:job_id>', views.send_message, name="send_message"),
    path('dashboard/<int:bid_id>/accept', views.accept_bid, name="accept_bid"),
    path('job/<int:job_id>', views.job_detail, name="job_detail"),
    path('job/<int:job_id>/dispute', views.dispute, name="dispute"),
    path('job/<int:job_id>/messenger', views.job_messenger, name="job_messenger"),
    path('dashboard/job/<int:job_id>/delete', views.delete_job, name="delete_job"),
    path('job/<int:job_id>/translate', views.translate, name="translate"),
    path('job/<int:job_id>/review', views.review, name="review"),
    path('job/<int:job_id>/review/rate', views.rate, name="rate"),
    path('messenger',views.messenger, name="messenger"),
]

translate_o_rama/urls.py
from django.contrib import admin
from django.urls import path, include


from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home_path'),
    path('app/', include('app.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from app.models import Profile,Job,Dispute,Message,Rating,Bid
from django.contrib.auth.models import User



# Create your views here.
@login_required
def dashboard(request):
    user = request.user
    my_jobs = user.job_set.all()
    my_bids = user.bid_set.all()
    accepted_jobs = user.profile.active_jobs()
    #completed_jobs = user.job_set.all().filter(status="completed")

    #assigned_jobs = user.bid_set().all().filter(bidder=user, accepted=True)

    won = user.bid_set.filter(accepted=True)

    rating_list = Rating.objects.all().filter(rated=user)
    sum_rating=0
    if len(rating_list) == 0:
        average=0
    else:
        for rating in rating_list:
            sum_rating=sum_rating+rating.rating
        average = sum_rating/len(rating_list)
        
    #my_accepted_bids = user.bid_set.all().filter(accepted=True)
    context = {
        'my_jobs': my_jobs,
        'my_bids': my_bids,
        #'my_accepted_bids': my_accepted_bids,
        #'accepted_jobs': accepted_jobs,
        #'completed_jobs': completed_jobs,
        'average': average,
        'won':won,
        #'assigned_jobs':assigned_jobs,
        
    }
    return render(request,'accounts/dashboard.html',context)

@login_required
def profile(request,user_id):
    user = get_object_or_404(User,pk=user_id)
    visitor = request.user

    accepted_jobs = Job.accepted_jobs_for(user)
    #completed_jobs = Job.objects.filter(user=user,status='completed')

    my_jobs = user.job_set.all()
    my_bids = user.bid_set.all()

    won = user.bid_set.filter(accepted=True)

    
    rating_list = Rating.objects.all().filter(rated=user)
    sum_rating=0
    if len(rating_list) == 0:
        average=0
    else:
        for rating in rating_list:
            sum_rating=sum_rating+rating.rating
        average = (sum_rating/len(rating_list))

    context = {
        'profile_user': user,
        'accepted_jobs': accepted_jobs,
        #'completed_jobs': completed_jobs,
        'average':average,
        'my_jobs': my_jobs,
        'my_bids': my_bids,
        'visitor': visitor,
        'won':won,
    }
    return render(request,'accounts/profile.html',context)

@login_required
def delete_bid(request, bid_id):
    bid = get_object_or_404(Bid, pk=bid_id)
    bid.delete()
    return HttpResponseRedirect(reverse("accounts:dashboard", args=[]))

@login_required
def change_email(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if request.POST["email"] != "":
        user.email = request.POST["email"]
        user.save()
    return HttpResponseRedirect(reverse("accounts:profile", args=[user.id]))

@login_required
def change_password(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if request.POST["password"] != "":
        user.email = request.POST["password"]
        user.save()
    return HttpResponseRedirect(reverse("accounts:profile", args=[user.id]))

accounts/templates/accounts/dashboard.html
{% extends 'app/base.html' %}
{% block content %}

<div class="card">
    <div class="card-body">
        <h1>Hello, {{ user.profile.name }}</h1>
        <div class="row">
            <div class="col-md-4">
                <p class="card-text">Token balance
                    <textarea class="form-control" readonly rows="1" style="resize:none">{{ user.profile.balance }}</textarea>
                </p>
            </div>
            <div class="col-md-4">
                <p class="card-text">Email
                    <textarea class="form-control" readonly rows="1" style="resize:none">{{ user.email }}</textarea>
                </p>
            </div>
            {% if user.profile.translator %}
                <div class="col-md-4">
                    <p class="card-text">Rating
                        <textarea class="form-control" readonly rows="1" style="resize:none">{{ average }}</textarea>
                    </p>
                </div>
            {% endif %}
        </div>
    </div>
</div><br>

<div class="card">
    <div class="card-header">
        <h1>My jobs</h1>
    </div>
    <div class="card-body">
        {% for job in my_jobs %}
            {% include 'includes/my_job_card.html' with job=job %}
            {% empty %}
                <p style="padding-left: 25px; color: #545454; margin-bottom: 7px">No jobs</p>
        {% endfor %}
    </div>
</div><br>

{% if user.profile.translator %}

    <div class="card">
        <div class="card-header">
            <h1>Submitted bids</h1>
        </div>
            <div class="card-body">
                {% for bid in my_bids %}
                    <div class="card">
                        <div class="card-header">
                            <h6>{{ bid.job.title }}</h6>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-9">
                                    Amount: {{ bid.price }} 
                                </div>
                                <div class="col-md-3">
                                    <a href="{% url 'accounts:delete_bid' bid.id %}" class="btn btn-danger">
                                        Delete
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div><br>
                    {% empty %}
                        <p style="padding-left: 25px; color: #545454; margin-bottom: 7px">No submitted bids</p>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <br>
        <div class="card">
            <div class="card-header">
                <h1>Assigned jobs</h1>
            </div>
                <div class="card-body">
                    {% for bid in won %}
                        {% if bid.job.status == "assigned" %}
                            {% include 'includes/job_card.html' with job=bid.job %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <br>
    <div class="card">
        <div class="card-header">
            <h1>Completed jobs</h1>
        </div>
            <div class="card-body">
                {% for bid in won %}
                    {% if bid.job.status == "completed" %}
                        {% include 'includes/job_card.html' with job=bid.job %}
                    {% endif %}
                {% empty %}
                    <p style="padding-left: 25px; color: #545454; margin-bottom: 7px">No completed jobs</p>
                {% endfor %}
            </div>
        </div>
    </div>
    
{% endif %}
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'app/base.html' %}
{% block content %}

<style>
    textarea {
        resize: none;
        background-color: white;
    }

    control[readonly]{
        background:white;
    }

    .checked {
        color: orange;
      }

</style>

<div class="container">
    <div class="card">
        <div class="card-header">
            <h1>{{ profile_user.profile.name }}'s profile name</h1>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <p class="card-text">Token balance
                        <textarea class="form-control" readonly rows="1" style="resize:none">{{ user.profile.balance }}</textarea>
                    </p>
                </div>
                <div class="col-md-4">
                    <p class="card-text">Email
                        <textarea class="form-control" readonly rows="1" style="resize:none">{{ user.email }}</textarea>
                    </p>
                </div>
                {% if user.profile.translator %}
                    <div class="col-md-4">
                        <p class="card-text">Rating
                            <textarea class="form-control" readonly rows="1" style="resize:none">{{ average }}</textarea>
                        </p>
                    </div>
                {% endif %}
            </div>
            <br>
            {% if profile_user == visitor %}
                <div class="row">
                    <div class="col-md-6">
                        <form method="post" action="{% url 'accounts:change_email' profile_user.id %}">
                            {% csrf_token %} 
                            <div class="form-group">
                                <label for="exampleInputEmail1">Email address</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" name="email" required>
                            </div>
                            <input type="submit" class="btn btn-primary" value="Change email">
                        </form>
                    </div>
                    <div class="col-md-6">
                        <form method="post" action="{% url 'accounts:change_password' profile_user.id %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="exampleInputEmail1">Password</label>
                                <input type="password" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter password" name="password" required>
                            </div>
                            <input type="submit" class="btn btn-primary" value="Change password">
                        </form>
                    </div>
                </div>
            {% endif %}
        </div>
    </div><br>
 
<div class="card">
    <div class="card-header">
        <h1>User's accepted jobs</h1>
    </div>
    <div class="card-body">
        {% for job in accepted_jobs %}
            {% include 'includes/job_card.html' with job=job %}
        {% empty %}
            <p style="padding-left: 25px; color: #545454; margin-bottom: 7px">No accepted jobs</p>
        {% endfor %}
    </div>
</div>
<br>
<div class="card">
    <div class="card-header">
        <h1>User's completed jobs</h1>
    </div>
    <div class="card-body">
        {% for job in completed_jobs %}
            {% include 'includes/job_card.html' with job=job %}
        {% empty %}
            <p style="padding-left: 25px; color: #545454; margin-bottom: 7px">No completed jobs</p>
        {% endfor %}
    </div>
</div><br>

{% if user.profile.translator %}
    <div class="card">
        <div class="card-header">
            <h1>My jobs</h1>
        </div>
        <div class="card-body">
            {% for job in my_jobs %}
                {% include 'includes/job_card.html' with job=job %}
                {% empty %}
                    <p style="padding-left: 25px; color: #545454; margin-bottom: 7px">No jobs</p>
            {% endfor %}
        </div>
    </div><br>

    <div class="card">
        <div class="card-header">
            <h1>Submitted bids</h1>
        </div>
            <div class="card-body">
                {% for bid in my_bids %}
                <div class="card">
                    <div class="card-header">
                        <h6>{{ bid.job.title }}</h6>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-9">
                                Amount: {{ bid.price }} 
                            </div>
                        </div>
                    </div>
                </div><br>
                {% empty %}
                    <p style="padding-left: 25px; color: #545454; margin-bottom: 7px">Submitted bids</p>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <br>
        <div class="card">
            <div class="card-header">
                <h1>Assigned jobs</h1>
            </div>
                <div class="card-body">
                    {% for bid in won %}
                        {% if bid.job.status == "assigned" %}
                            {% include 'includes/job_card.html' with job=bid.job %}
                        {% endif %}
                        {% empty %}
                            <p style="padding-left: 25px; color: #545454; margin-bottom: 7px">No assigned jobs</p>
                    {% endfor %}
                </div>
            </div>
        </div>
        <br>
        <div class="card">
            <div class="card-header">
                <h1>Completed jobs</h1>
            </div>
            <div class="card-body">
                {% for bid in won %}
                    {% if bid.job.status == "completed" %}
                        {% include 'includes/job_card.html' with job=bid.job %}
                    {% endif %}
                {% empty %}
                    <p style="padding-left: 25px; color: #545454; margin-bottom: 7px">No completed jobs</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
   
    
{% endif %}

{% endblock content %}