accounts/urls.py
from django.urls import path
from .import views
app_name = "accounts"
urlpatterns=[
    path('dashboard',views.dashboard,name="dashboard"),
    path('profile/<int:user_id>',views.profile,name="profile"),
    path('dashboard/bid/<int:bid_id>/delete', views.delete_bid, name="delete_bid"),
    path('profile/<int:user_id>/change_email', views.change_email, name="change_email"),
    path('profile/<int:user_id>/change_password', views.change_password, name="change_password"),
]

app/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    path('', views.index, name="index"),
    path('register', views.registration, name="registration"),
    path('user_login', views.custom_login, name="custom_login"),
    path('job_form', views.job_form, name="job_form"),
    path('job_form/save', views.save_job, name="save_job"),
    path('all_jobs', views.all_jobs, name="all_jobs"),
    path('all_jobs/bid/<int:job_id>', views.bid, name="bid"),
    path('all_jobs/send_message/<int:job_id>', views.send_message, name="send_message"),
    path('dashboard/<int:bid_id>/accept', views.accept_bid, name="accept_bid"),
    path('job/<int:job_id>', views.job_detail, name="job_detail"),
    path('job/<int:job_id>/dispute', views.dispute, name="dispute"),
    path('job/<int:job_id>/messenger', views.job_messenger, name="job_messenger"),
    path('dashboard/job/<int:job_id>/delete', views.delete_job, name="delete_job"),
    path('job/<int:job_id>/translate', views.translate, name="translate"),
    path('job/<int:job_id>/review', views.review, name="review"),
    path('job/<int:job_id>/review/rate', views.rate, name="rate"),
    path('messenger',views.messenger, name="messenger"),
]

translate_o_rama/urls.py
from django.contrib import admin
from django.urls import path, include


from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home_path'),
    path('app/', include('app.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

app/templates/app/base.html
{% load static %}
<html>
  <head>
    <title>Translate-o-rama</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>
    <!--<link rel="stylesheet" href="{% static 'app/css/app.css' %}">-->
    <link rel="stylesheet" href="{% static 'app/css/translatorama.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <div class="page-header">
      <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-normal" style="background: #f8f9fa">
        <a class="navbar-brand" href="/">Translate-o-rama</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                {% if user.profile.is_translator %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'app:all_jobs' %}">Jobs</a>
                    </li>
                {% endif %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'app:job_form' %}">Post a Job</a>
                    </li>
            </ul>
          {% endif %}

          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'app:messenger' %}">Messenger</a>
                </li>
                {% if user.is_superuser %}
                    <li class="nav-item active">
                        <a class="nav-link" href="/admin/">Admin dashboard</a>
                    </li>
                {% endif %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'accounts:profile' user.id %}">Profile</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:dashboard' %}">{{user.profile.name}}</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'logout' %}" style="color: rgba(255,0,0,0.81); background: transparent;">Log out</a>
                </li>

            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'app:custom_login' %}" style="color: rgba(31,81,231,0.82);)">Login</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'app:registration' %}">Register</a>
                </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
    
    <div class="content container" style="margin-top: 5%">
      <div class="row">
        <div class="col-md-12">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>

  </body>
</html>

app/templates/app/dispute.html
{% extends 'app/base.html' %}
{% block content %}

    <h1>Dispute on {{ job.title }}</h1>
    <form method="post" action="{% url 'app:dispute' job.id%}">
        {% csrf_token %}
        <label for="reason">Reason:</label>
        <br>
        <textarea id="reason" name="reason" required></textarea>
        <br><br>
        <input type="submit" class="btn btn-danger" value="File a dispute">
    </form>

{% endblock content %}

app/templates/app/home.html
{% extends 'app/base.html' %}
{% block content %}


<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
    <div class="col-md-12 p-lg-5 mx-auto my-5">
      <h1 class="display-4 font-weight-normal">Welcom to Translate-o-rama</h1>
      <p class="lead font-weight-normal">Come and join us, share and translate a variaty of text</p>
    </div>
 </div>

{% endblock content %}

app/templates/app/job_detail.html
{% extends 'app/base.html' %}
{% block content %}


<div class="card">
    <div class="card-header">
        <h2>{{ job.title }}</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-6">
                        <p class="card-text">Source language
                            <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.source_lang }}</textarea>
                        </p>
                    </div>
                    <div class="col-md-6">
                        <p class="card-text">Target language 
                            <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.target_lang }}</textarea>
                        </p>
                    </div>
                </div>
            </div>
        </div><br>
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-6">
                        <p class="card-text">Field
                            <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.field }}</textarea>
                        </p>
                    </div>
                    <div class="col-md-6">
                        <p class="card-text">Budget
                            <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.budget }}</textarea>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="exampleFormControlTextarea1">Text</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="13" name="translate_text" readonly style="resize:none; background:white">{{ job.text }}</textarea>
                </div>
            </div>
            <div class="col-md-6">
                {% if visitor == translator.user and job.status != "completed" and job.translation == "" %}
                    <form method="post" action="{% url 'app:translate' job.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="exampleFormControlTextarea1">Translation</label>
                            <textarea class="form-control" id="exampleFormControlTextarea1" rows="13" name="translate_text" style="resize:none;" required>{{ job.translation }}</textarea>
                        </div>
                        <input type="submit" value="Translate" class="btn btn-primary">
                    </form>
                {% else %}
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Translation</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="13" name="translate_text" readonly style="resize:none; background:white">{{ job.translation }}</textarea>
                    </div>
                {% endif %}
                
            </div>
        </div>
        
            <a class="btn btn-primary" href="{% url 'app:job_messenger' job.id %}">
                Messages
            </a>
            {% if job.status == "completed"%}
                <a href="{% url 'app:dispute' job.id %}" class="btn btn-danger">Dispute</a>
            {% endif %}
    </div>
</div>



{% endblock %}

app/templates/app/job_messenger.html
{% extends 'app/base.html' %}
{% block content %}

<!--
<div class="row">
    <div class="col-md-12">
        <div class="col-md-4"></div>
        <div class="col-md-8">
            {% include 'includes/messenger-card.html' with messages=messages %}
        </div>
    </div>
</div>-->

<style>
    .bubble {
         border-radius: 1em;
         padding: 0.25em 0.75em;
         margin: 0.0625em;
         with: 100px;
         word-wrap: break-word;
     }
     
     .bubble.sender {
         align-self: flex-start;
         background-color: cornflowerblue;
         color: #fff;
     }
 
     .bubble.recipient {
         align-self: flex-end;
         background-color: #efefef;
     }
     
     small{
         padding-left:10px;
     }
 
     p{
         padding: 5px;
     }
 
     .bubble.sender{
         text-align:left;
         width: fit-content;
     }
 
     .bubble.recipient {
         width: fit-content;
     }
 
     .smth{
         float: right;
     }

     #messenger{
        margin-left: auto;
        top:10%;
     }

     .card-footer{
        vertical-align:middle;
     }

     form{
        margin-bottom: 0;
     }
 </style>

<div class="card">
    <div class="card-header">
        <h2>Messenger</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body" style="overflow-y:auto; max-height:558px; height:558px; ">
                        {% if user.translator %}
                            {% for job in my_jobs %}
                                <div class="card">
                                    <div class="card-header">
                                        <a href="{% url 'app:job_messenger' job.id %}">
                                            <h6>{{ job.title }}<h6>
                                        </a>
                                    </div>
                                    <div class="card-body">
                                        <p>
                                            {{ job.description }}
                                        </p>
                                    </div>
                                </div><br>
                            {% endfor %}
                            {% for bid in assigned_jobs %}
                                <div class="card">
                                    <div class="card-header">
                                        <a href="{% url 'app:job_messenger' bid.job.id %}">
                                            <h6>{{ bid.job.title }}<h6>
                                        </a>
                                    </div>
                                    <div class="card-body">
                                        <p>
                                            {{ bid.job.description }}
                                        </p>
                                    </div>
                                </div><br>
                            {% endfor %}
                            {% if my_jobs.count == 0 and assigned_jobs.count == 0 %}
                                {% for message in my_messages %}
                                    <div class="card">
                                        <div class="card-header">
                                            <a href="{% url 'app:job_messenger' message.job.id %}">
                                                <h6>{{ message.job.title }}<h6>
                                            </a>
                                        </div>
                                        <div class="card-body">
                                            <p>
                                                {{ message.job.description }}
                                            </p>
                                        </div>
                                    </div><br>
                                {% endfor %}
                            {% endif %}
                        {% else %}
                            {% for job in my_jobs %}
                                <div class="card">
                                    <div class="card-header">
                                        <a href="{% url 'app:job_messenger' job.id %}">
                                            <h6>{{ job.title }}<h6>
                                        </a>
                                    </div>
                                    <div class="card-body">
                                        <p>
                                            {{ job.description }}
                                        </p>
                                    </div>
                                </div><br>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body" >
                        {% include 'includes/messenger-card.html' with messages=messages %}
                       
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

app/templates/app/jobs.html
{% extends 'app/base.html' %}
{% block content %}

{% for job in jobs %}

<div class="card">
  <div class="card-header">{{ job.title }}</div>
  <div class="card-body">
    <div class="row">
      <div class="col-md-4">
        <p class="card-text">Source language
          <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.source_lang }}</textarea>
        </p><br>
        <p class="card-text">Target language 
          <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.target_lang }}</textarea>
        </p>
      </div>
      <div class="col-md-4">
        <p class="card-text">Field
          <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.field }}</textarea></p><br>
        <p class="card-text">Budget
          <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.budget }}</textarea></p>
      </div>
      <div class="col-md-4">
        <form method="POST" action="{% url 'app:bid' job.id %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="exampleFormControlInput1">Amount</label>
            <input type="number" step="0.50" class="form-control" id="exampleFormControlInput1" placeholder="0.00" name="price">
          </div>
          <input type="submit" value="Bid" class="btn btn-primary">
        </form>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-8">
        <p class="card-text">
          Description
          <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.description }}</textarea>
        </p><br>
        <p>
          Text
          <textarea class="form-control" readonly>{{ job.text }}</textarea>
        </p>
      </div>
      <div class="col-md-4">
        <a class="btn btn-primary" href="{% url 'app:job_messenger' job.id %}">
          Message author
        </a>
      </div>
    </div>
    
  </div>
</div><br>

{% endfor %}
{% endblock %}

app/templates/app/messenger.html
{% extends 'app/base.html' %}
{% block content %}

<div class="card">
    <div class="card-header">
        <h2>Messenger</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body" style="overflow-y:auto; max-height:558px; height:558px; ">
                        {% if user.translator %}
                            {% for job in my_jobs %}
                                <div class="card">
                                    <div class="card-header">
                                        <a href="{% url 'app:job_messenger' job.id %}">
                                            <h6>{{ job.title }}<h6>
                                        </a>
                                    </div>
                                    <div class="card-body">
                                        <p>
                                            {{ job.description }}
                                        </p>
                                    </div>
                                </div><br>
                            {% endfor %}
                            {% for bid in assigned_jobs %}
                                <div class="card">
                                    <div class="card-header">
                                        <a href="{% url 'app:job_messenger' bid.job.id %}">
                                            <h6>{{ bid.job.title }}<h6>
                                        </a>
                                    </div>
                                    <div class="card-body">
                                        <p>
                                            {{ bid.job.description }}
                                        </p>
                                    </div>
                                </div><br>
                            {% endfor %}
                            {% if my_jobs.count == 0 and assigned_jobs.count == 0 %}
                                {% for message in my_messages %}
                                    <div class="card">
                                        <div class="card-header">
                                            <a href="{% url 'app:job_messenger' message.job.id %}">
                                                <h6>{{ message.job.title }}<h6>
                                            </a>
                                        </div>
                                        <div class="card-body">
                                            <p>
                                                {{ message.job.description }}
                                            </p>
                                        </div>
                                    </div><br>
                                {% endfor %}
                            {% endif %}
                        {% else %}
                            {% for job in my_jobs %}
                                <div class="card">
                                    <div class="card-header">
                                        <a href="{% url 'app:job_messenger' job.id %}">
                                            <h6>{{ job.title }}<h6>
                                        </a>
                                    </div>
                                    <div class="card-body">
                                        <p>
                                            {{ job.description }}
                                        </p>
                                    </div>
                                </div><br>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
                            <div class="col-md-12 p-lg-4 mx-auto my-5">
                              <h1 class="display-4 font-weight-normal">Welcom to TR-Messenger</h1>
                             
                            </div>
                         </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/app/post_job.html
{% extends 'app/base.html' %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h1>Submit new job</h1>
        </div>
        <div class="card-body">
            <form method="post" action="{% url 'app:save_job' %}">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group">
                        <label for="exampleFormControlInput1">Title</label>
                        <input type="text" class="form-control" id="exampleFormControlInput1" name="title" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlInput1">Description</label>
                        <input type="text" class="form-control" id="exampleFormControlInput1" name="description" required>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="exampleFormControlInput1">Souorce language</label>
                                <input type="text" class="form-control" id="exampleFormControlInput1" name="source_language" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="exampleFormControlInput1">Target language</label>
                                <input type="text" class="form-control" id="exampleFormControlInput1" name="target_language" required>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlSelect1">Field</label>
                        <select class="form-control" id="exampleFormControlSelect1" name="job_field">
                            <option value="art">Art</option>
                            <option value="business">Business</option>
                            <option value="computers">Computers</option>
                            <option value="education">Education</option>
                            <option value="engineering">Engineering</option>
                            <option value="finance">Finance</option>
                            <option value="law">Law</option>
                            <option value="literature">Literature</option>
                            <option value="medicine">Medicine</option>
                            <option value="science">Science</option>
                            <option value="social">Social</option>
                            <option value="technology">Technology</option>
                        </select>
                      </div>
                    <div class="form-group">
                        <label for="exampleFormControlInput1">Budget</label>
                        <input type="number" class="form-control" id="exampleFormControlInput1" name="budget" step="0.5" required>
                    </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="exampleFormControlTextarea1">Text</label>
                            <textarea class="form-control" id="exampleFormControlTextarea1" rows="13" name="translate_text" style="resize:none" required></textarea>
                        </div>
                        <input type="submit" value="Post job" class="btn btn-primary">
                    </div>
                </div>
            </form>
        
        </div>
    </div>
   
{% endblock %}

app/templates/app/review.html
{% extends 'app/base.html' %}
{% block content %}

    <div class="card">
        <div class="card-header">
            <h2>
                {{ job.title }}
            </h2>

        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Text</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="13" name="translate_text" readonly style="resize:none; background:white">{{ job.text }}</textarea>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Translation</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="13" name="translate_text" readonly style="resize:none; background:white">{{ job.translation }}</textarea>
                    </div>
                </div>
            </div>
            {% if visitor == job.user %}
                <div class="row">
                    <div class="col-md-6">
                        <form method="post" action="{% url 'app:rate' job.id %}">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="1">
                                        <label class="form-check-label" for="inlineRadio1">1</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="2">
                                        <label class="form-check-label" for="inlineRadio2">2</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="3">
                                        <label class="form-check-label" for="inlineRadio1">3</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="4">
                                        <label class="form-check-label" for="inlineRadio2">4</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="5">
                                        <label class="form-check-label" for="inlineRadio1">5</label>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-6">
                                    <input type="submit" value="Rate and approve" class="btn btn-primary">
                                </div>
                            </div>
                            
                        </form>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>


{% endblock %}