accounts/urls.py
from django.urls import path
from .import views
app_name = "accounts"
urlpatterns=[
    path('dashboard',views.dashboard,name="dashboard"),
    path('profile/<int:user_id>',views.profile,name="profile"),
    path('dashboard/bid/<int:bid_id>/delete', views.delete_bid, name="delete_bid"),
    path('profile/<int:user_id>/change_email', views.change_email, name="change_email"),
    path('profile/<int:user_id>/change_password', views.change_password, name="change_password"),
]

app/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    path('', views.index, name="index"),
    path('register', views.registration, name="registration"),
    path('user_login', views.custom_login, name="custom_login"),
    path('job_form', views.job_form, name="job_form"),
    path('job_form/save', views.save_job, name="save_job"),
    path('all_jobs', views.all_jobs, name="all_jobs"),
    path('all_jobs/bid/<int:job_id>', views.bid, name="bid"),
    path('all_jobs/send_message/<int:job_id>', views.send_message, name="send_message"),
    path('dashboard/<int:bid_id>/accept', views.accept_bid, name="accept_bid"),
    path('job/<int:job_id>', views.job_detail, name="job_detail"),
    path('job/<int:job_id>/dispute', views.dispute, name="dispute"),
    path('job/<int:job_id>/messenger', views.job_messenger, name="job_messenger"),
    path('dashboard/job/<int:job_id>/delete', views.delete_job, name="delete_job"),
    path('job/<int:job_id>/translate', views.translate, name="translate"),
    path('job/<int:job_id>/review', views.review, name="review"),
    path('job/<int:job_id>/review/rate', views.rate, name="rate"),
    path('messenger',views.messenger, name="messenger"),
]

translate_o_rama/urls.py
from django.contrib import admin
from django.urls import path, include


from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home_path'),
    path('app/', include('app.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

app/templates/includes/bid_card.html
{% if bid.accepted %}
<style>
    #accepted_bid{
        background: green;
    }

    #accept_bid a{
        text-decoration: none;
        color:white;
    }
</style>
{% endif %}

<div class="card">
    {% if bid.accepted %}
        <div class="card-header" id="accepted_bid" >
            <a href="{% url 'accounts:profile' bid.bidder.id %}" style=" color:white;"><h6>{{ bid.bidder.profile.name }}</h6></a>
        </div>
    {% else %}
        <div class="card-header" >
            <h6>{{ bid.bidder.profile.name }}</h6>
        </div>
    {% endif %}
    <div class="card-body">
        <div class="row">
            <div class="col-md-9">
                Amount: {{ bid.price }}
            </div>
            <div class="col-md-3">
                {% if not bid.accepted %}
                    <a href="{% url 'app:accept_bid' bid_id=bid.id %}" class="btn btn-success">
                        Accept
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</div><br>

app/templates/includes/job_card.html
<div class="card">
    <div class="card-header">
        <a href="{% url 'app:job_detail' job.id %}">
           <h3>{{ job.title }}</h3> 
        </a>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <p class="card-text">Source language
                    <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.source_lang }}</textarea>
                </p>
            </div>
            <div class="col-md-6">
                <p class="card-text">Target language 
                  <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.target_lang }}</textarea>
                </p>
            </div>
        </div><br>
        <div class="row">
            <div class="col-md-6">
                <p class="card-text">Field
                    <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.field }}</textarea>
                </p>
            </div>
            <div class="col-md-6">
                <p class="card-text">Budget
                <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.budget }}</textarea>
                </p>
            </div>
        </div><br>
        <p class="card-text">
            Description
            <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.description }}</textarea>
        </p>
        {% if job.status == "completed" %}
            <a href="{% url 'app:review' job.id %}" class="btn btn-primary">
                View translation
            </a>
        {% endif %}
    </div>
</div><br>

app/templates/includes/messenger-card.html
<style>
    .bubble {
         border-radius: 1em;
         padding: 0.25em 0.75em;
         margin: 0.0625em;
         with: 100px;
         word-wrap: break-word;
     }
     
     .bubble.sender {
         align-self: flex-start;
         background-color: cornflowerblue;
         color: #fff;
     }
 
     .bubble.recipient {
         align-self: flex-end;
         background-color: #efefef;
     }
     
     small{
         padding-left:10px;
     }
 
     p{
         padding: 5px;
     }
 
     .bubble.sender{
         text-align:left;
         width: fit-content;
     }
 
     .bubble.recipient {
         width: fit-content;
     }
 
     .smth{
         float: right;
     }

     #messenger{
        margin-left: auto;
        top:10%;
     }

     .card-footer{
        vertical-align:middle;
     }

     form{
        margin-bottom: 0;
     }
 </style>
 

        <div class="card" id="messenger">
            <div class="card-header">
                Messenger - {{ job.title }}
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12" style="overflow-y:auto; max-height:350px; height:350px; ">
                        {% for message in messages %}
                            {% if message.sender == user %}
                                <div class="row">
                                    <div class="col-md-6"></div>
                                    <div class="col-md-6" style="align-items:right">
                                        <div class="smth">
                                           <small>{{ message.sender.username }}</small>
                                            <p class="bubble sender">
                                                {{ message.text }}
                                            </p> 
                                        </div>
                                    </div>
                                </div>
                            {% elif message.reciever == job.user %}
                            <div class="row">
                                <div class="col-md-6">
                                    <small>{{ message.sender.username }}</small>
                                    <p class="bubble recipient">
                                    {{ message.text }}  
                                    </p>
                                </div>
                                <div class="col-md-6"></div>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <form method="post" action="{% url 'app:send_message' job.id %}">
                    {% csrf_token %}
                        <div class="row">
                            <div class="col-md-9">
                                <div class="form-group">
                                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="1" name="message" style="resize:none" placeholder="Message" required></textarea>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <input type="submit" class="btn btn-primary" value="Send">
                            </div>
                        </div>
                </form>
            </div>
        </div>

app/templates/includes/my_job_card.html
<div class="card">
    <div class="card-header">
        <a href="{% url 'app:job_detail' job.id %}">
            <h3>{{ job.title }}</h3>
        </a>
        
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-6">
                        <p class="card-text">Source language
                            <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.source_lang }}</textarea>
                        </p>
                    </div>
                    <div class="col-md-6">
                        <p class="card-text">Target language 
                          <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.target_lang }}</textarea>
                        </p>
                    </div>
                </div><br>
                <div class="row">
                    <div class="col-md-6">
                        <p class="card-text">Field
                            <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.field }}</textarea>
                        </p>
                    </div>
                    <div class="col-md-6">
                        <p class="card-text">Budget
                          <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.budget }}</textarea>
                        </p>
                    </div>
                </div><br>
                <div class="row">
                    <div class="col-md-12">
                        <p class="card-text">
                            Description
                            <textarea class="form-control" readonly rows="1" style="resize:none">{{ job.description }}</textarea>
                        </p>
                        <p>
                            Text
                            <textarea class="form-control" rows="6" readonly style="resize:none">{{ job.text }}</textarea>
                        </p>
                        <a href="{% url 'app:job_messenger' job.id %}" class="btn btn-primary">
                            View messeges
                        </a>
                     
                        <a href="{% url 'app:delete_job' job.id %}" class="btn btn-danger">
                            Delete job
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card" >
                    <div class="card-header">
                        <h4>Bids</h4>
                    </div>
                    <div class="card-body" style="overflow-y:auto; max-height:370px">
                        {% for bid in job.bid_set.all %}
                            {% if bid.bidder != user %}
                                {% include 'includes/bid_card.html' with bid=bid %}
                            {% endif %}
                        {% empty %}
                            <p style="padding-left: 25px; color: #545454; margin-bottom: 7px">No bids</p>
                        {% endfor %}
                    </div>
                </div>
                <br>
            </div>
        </div>
    </div>
</div><br>

app/templates/includes/translator_bids.html
<div class="card">
    <div class="card-header">
        <h1>Submitted bids</h1>
    </div>
        <div class="card-body">
            {% for bid in bids %}
                <div class="card">
                    <div class="card-header">
                        <h6>{{ bid.job.title }}</h6>
                    </div>
                    <div class="card-body">
                        <h6>{{ bid.price }}</h6>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div><br>
    

app/templates/includes/translator_jobs.html
<div class="card">
    <div class="card-header">
        <h1>Assigned jobs</h1>
    </div>
        <div class="card-body">
            {% for job in jobs %}
                <div class="card">
                    <div class="card-header">
                        <h6>{{ job.title }}</h6>
                    </div>
                    <div class="card-body">
                        <h6>{{ job.description }}</h6>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
<br>